spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true