server:
  port: 8081

spring:
  application:
    name: task-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/task_db
      database: task_db

application:
  config:
    user-service-url: http://localhost:8080
    notification-service-url: http://localhost:8082

logging:
  level:
    com.lucas.taskservice.client: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full
