name: Java CI Monorepo

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Define a matriz com os nomes das pastas dos seus microsserviços.
    # O GitHub Actions vai rodar os testes dos 3 serviços em paralelo!
    strategy:
      matrix:
        service: [user-service, task-service, notification-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 # Ajuste para 21 se o seu Java for o 21
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and Test ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          chmod +x gradlew
          ./gradlew build
